# Generated by Django 4.2.4 on 2023-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=36)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('published', models.BooleanField(default=False)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
